"""add user_id to Todo Model

Revision ID: 5b294e48ef98
Revises: ad9f56bdf3e3
Create Date: 2024-08-15 17:11:23.869462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b294e48ef98'
down_revision = 'ad9f56bdf3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])

    # Update existing rows with a default user_id
    op.execute("UPDATE \"Todo\" SET user_id = 1 WHERE user_id IS NULL")

    # Make user_id not nullable after updating existing rows
    with op.batch_alter_table('Todo', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###